name: "Feature request"
description: "Suggest an idea for this projec"
labels: 'Type: enhancement'
body:
- type: markdown
  attributes:
    value: "Is your feature request related to a problem? Please describe."
- type: textarea
  id: description
  attributes:
    label: "Description of your suggestion"
    description: "Explain your idea with screenshoots, example, etc"
    placeholder: "Explain your idea"
  validations:
    required: true
