module.exports = {
    'clear': {
    },
    'bass': {
        'equalizer': [
            { 'band': 0, 'gain': 0.6 },
            { 'band': 1, 'gain': 0.67 },
            { 'band': 2, 'gain': 0.67 },
            { 'band': 3, 'gain': 0 },
            { 'band': 4, 'gain': -0.5 },
            { 'band': 5, 'gain': 0.15 },
            { 'band': 6, 'gain': -0.45 },
            { 'band': 7, 'gain': 0.23 },
            { 'band': 8, 'gain': 0.35 },
            { 'band': 9, 'gain': 0.45 },
            { 'band': 10, 'gain': 0.55 },
            { 'band': 11, 'gain': 0.6 },
            { 'band': 12, 'gain': 0.55 },
            { 'band': 13, 'gain': 0 },
        ],
    },
    'pop': {
        'equalizer': [
            { 'band': 0, 'gain': 0.65 },
            { 'band': 1, 'gain': 0.45 },
            { 'band': 2, 'gain': -0.45 },
            { 'band': 3, 'gain': -0.65 },
            { 'band': 4, 'gain': -0.35 },
            { 'band': 5, 'gain': 0.45 },
            { 'band': 6, 'gain': 0.55 },
            { 'band': 7, 'gain': 0.6 },
            { 'band': 8, 'gain': 0.6 },
            { 'band': 9, 'gain': 0.6 },
            { 'band': 10, 'gain': 0 },
            { 'band': 11, 'gain': 0 },
            { 'band': 12, 'gain': 0 },
            { 'band': 13, 'gain': 0 },
        ],
    },
    'soft': {
        'equalizer': [
            { 'band': 0, 'gain': 0 },
            { 'band': 1, 'gain': 0 },
            { 'band': 2, 'gain': 0 },
            { 'band': 3, 'gain': 0 },
            { 'band': 4, 'gain': 0 },
            { 'band': 5, 'gain': 0 },
            { 'band': 6, 'gain': 0 },
            { 'band': 7, 'gain': 0 },
            { 'band': 8, 'gain': -0.25 },
            { 'band': 9, 'gain': -0.25 },
            { 'band': 10, 'gain': -0.25 },
            { 'band': 11, 'gain': -0.25 },
            { 'band': 12, 'gain': -0.25 },
            { 'band': 13, 'gain': -0.25 },
        ],
    },
    'treblebass': {
        'equalizer': [
            { 'band': 0, 'gain': 0.6 },
            { 'band': 1, 'gain': 0.67 },
            { 'band': 2, 'gain': 0.67 },
            { 'band': 3, 'gain': 0 },
            { 'band': 4, 'gain': -0.5 },
            { 'band': 5, 'gain': 0.15 },
            { 'band': 6, 'gain': -0.45 },
            { 'band': 7, 'gain': 0.23 },
            { 'band': 8, 'gain': 0.35 },
            { 'band': 9, 'gain': 0.45 },
            { 'band': 10, 'gain': 0.55 },
            { 'band': 11, 'gain': 0.6 },
            { 'band': 12, 'gain': 0.55 },
            { 'band': 13, 'gain': 0 },
        ],
    },
    'bass': {
        'equalizer': [
            { 'band': 0, 'gain': 0.2 },
            { 'band': 1, 'gain': 0.3 },
            { 'band': 2, 'gain': 0 },
            { 'band': 3, 'gain': 0.8 },
            { 'band': 4, 'gain': 0 },
            { 'band': 5, 'gain': 0.5 },
            { 'band': 6, 'gain': 0 },
            { 'band': 7, 'gain': -0.5 },
            { 'band': 8, 'gain': 0 },
            { 'band': 9, 'gain': 0 },
            { 'band': 10, 'gain': 0 },
            { 'band': 11, 'gain': 0 },
            { 'band': 12, 'gain': 0 },
            { 'band': 13, 'gain': 0 },
        ],
    },
    'nightcore': {
        equalizer: [
            { band: 1, gain: 0.3 },
            { band: 0, gain: 0.3 },
        ],
        timescale: { pitch: 1.2 },
        tremolo: { depth: 0.3, frequency: 14 },
    },
    'vaporwave': {
        equalizer: [
            { band: 1, gain: 0.3 },
            { band: 0, gain: 0.3 },
        ],
        timescale: { pitch: 0.5 },
        tremolo: { depth: 0.3, frequency: 14 },
    },
};